[package]
name = "rust-wavelet-trees"
version = "0.1.0"
authors = ["Alexander Hahn <43539214+halex97@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bio = "0.28.1"
bv = "0.10.0"
rand = "0.7.0"